spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.199.206.241:3306/eshop?useSSL=false&characterEncoding=UTF-8
    username: root
    password: 123456
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:/mapper/*.xml
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8