spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.151:3306/eshop
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:/mapper/*.xml
server:
  port: 80

logging:
  level:
    org:
      springframework: WARN
    jxufe.lwl.eshop.dao: DEBUG